packages:
  - codex-cli
  - docs
  - packages/*

ignoredBuiltDependencies:
  - esbuild

overrides:
  braces: ^3.0.3
  micromatch: ^4.0.8
  semver: ^7.7.1
  codex-monorepo: 'link:'
  '@openai/codex': link:codex-cli
